ProyectoJR/Blog/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from Blog.views import editarNoticiasClass
from Blog import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^new',views.insertar_noticia, name = 'InsertarNoticia'),
    url(r'^(?P<noticia_id>\d+)$', views.mostrar_noticia, name ='MostrarNoticia'),
    url(r'^edit/(?P<id_noticia>\d+)$',views.editarNoticia, name = 'EditarNoticia'),
    url(r'^borrar/(?P<noticia>\d+)$',views.borrarNoticia, name = 'BorrarNoticia'),
    #url(r'^',views.editarNoticias, name = 'EditarNoticias'),
    url(r'^$', login_required(editarNoticiasClass.as_view()), name = 'EditarNoticias'),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

ProyectoJR/ProyectoJR/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from Blog import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^noticias/',include('Blog.urls', namespace="urlNoticias")),
    url(r'^categoria/(?P<nombreCat>\w{0,50})$',views.categoria, name="filtro_categoria"),
    url(r'^categoria/borrar/(?P<Cat>\w{0,50})$',views.borrarCategoria, name="borrarCategoria"),
    url(r'^categoria/edit/(?P<id_categ>\w{0,50})$',views.editarCategoria, name="editarCategoria"),
    url(r'^categoria/new/', views.insertar_categoria, name="nuevaCategoria"),
    url(r'^categorias/', login_required(views.editarCategoriasClass.as_view()), name="Ccategoria"),
    url(r'^comentario/borrar/(?P<coment>\w{0,50})$',views.borrarComentario, name="borraComentario"),
    url(r'^comentarios/', login_required(views.editarComentariosClas.as_view()), name="comentario"),
    url(r'^autor/(?P<nombreAut>\w{0,50})/$',views.autor, name="autor"),
    url(r'^search/',views.search),
    url(r'^users/',include('Users.urls', namespace = "users")),
    url(r'^$',views.index, name = "index"),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

ProyectoJR/Users/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from Users.views import userLogin, userLogout, registro
from Users import views
from django.contrib.auth.forms import AdminPasswordChangeForm

urlpatterns = [
    #url(r'^register/$', RegisterUser.as_view(), name = "register"),
    #url(r'^update/(?P<pk>\d+)/$', UpdateProfile.as_view(), name = "update"),
    url(r'^login', userLogin.as_view(), name = 'login'),
    url(r'^logout', userLogout.as_view(), name = 'logout'),
    url(r'^registro', views.registro, name = 'registro'),
    url(r'^editarPerfil', views.editarUsuario, name = 'editarPerfil'),
    url(r'^cambiarPass', views.changePass ,name = 'cambiarPass' ),    
    url(r'^edit/(?P<id_usuario>\w{0,50})$', views.editUser, name = 'editarUsuario'),    
    url(r'^borrar/(?P<id_u>\w{0,50})$', views.borrarUsuario, name = 'borrarUsuario'),        
    url(r'^', views.editarUsuarios, name = 'editarUsuarios'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

ProyectoJR/Users/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class blogUsers(User):
	Tipos = (
		('0', 'Lector'),
		('1', 'Autor'),
		('2', 'Administrador'),
	)
	Estados = (
		('0', 'Desactivado'),
		('1', 'Activado'),
	)
	Tipo = models.CharField(max_length=1,choices=Tipos)
	Estado = models.CharField(max_length=1,choices=Estados)
    
	def __unicode__(self):
		return self.username

ProyectoJR/Users/forms.py
#encoding: utf-8
from django.forms.extras.widgets import SelectDateWidget
from django.forms import ModelForm
from django import forms
from django.contrib.auth.forms import UserCreationForm
from Users.models import blogUsers
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):

    class Meta:
        model = blogUsers
        fields = ['first_name', 'last_name', 'username', 'email']
        
class changeUser(ModelForm):
	class Meta:
		model = User
		fields = ['username','first_name', 'last_name', 'email']
        
	def __init__(self, *args, **kwargs):
	    super(changeUser, self).__init__(*args,**kwargs)	    
	    self.fields['username'].widget.attrs['readonly'] = True
	    self.fields['username'].help_text = None  
	    self.fields['email'].help_text = None  
	    self.fields['first_name'].help_text = None  
	    self.fields['last_name'].help_text = None  	    	    

	    	    	         
class UserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2",'first_name', 'last_name')

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

class editUserA(ModelForm):
    class Meta:
        model = User
        fields = ["username", "email",'first_name', 'last_name','is_staff','is_superuser']

    def __init__(self, *args, **kwargs):
	    super(editUserA, self).__init__(*args,**kwargs)	    
	    self.fields['username'].help_text = None
	    self.fields['email'].help_text = None
	    self.fields['first_name'].help_text = None
	    self.fields['last_name'].help_text = None
	    self.fields['is_staff'].help_text = None
	    self.fields['is_superuser'].help_text = None
	   

ProyectoJR/Users/views.py
from django.conf import settings
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect, render_to_response
from django.template import RequestContext
from django.utils.decorators import method_decorator
from django.views.generic import RedirectView
from django.views.generic.edit import FormView
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm

from Users.forms import UserCreationForm, editUserA,changeUser
from Users.forms import blogUsers


# Create your views here.

# Login User
class userLogin(FormView):
    model = blogUsers
    form_class = AuthenticationForm
    template_name = 'Users/login_form.html'
    success_url = reverse_lazy('index')

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return redirect(self.get_success_url())
        else:
            context = {'form': AuthenticationForm}
            return super(userLogin, self).get(request, *args, **kwargs)

    def form_valid(self, form):
        login(self.request, form.get_user())
        return redirect(self.get_success_url())


class userLogout(RedirectView):
    url = reverse_lazy('index')
    settings.LOGIN_URL = '/users/login/'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(userLogout, self).dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        logout(request)
        return super(userLogout, self).get(request, *args, **kwargs)


def registro(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            context = {'form': AuthenticationForm}
            return redirect(reverse_lazy('users:login'))
        else:
            return render(request, "Users/registro_form.html", {'form': form,})
    else:
        form = UserCreationForm()
        return render(request, "Users/registro_form.html", {'form': form,})

@login_required(login_url='/users/login')
def editarUsuario(request):
    if request.method == 'POST':
        request.POST = request.POST.copy()
        request.POST['username'] = request.user.username
        form = changeUser(request.POST,instance=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, request.user)
            context = {'form': form}
            return redirect(reverse_lazy('users:editarPerfil'))
        else:
            return render(request, "Users/editarUsuario.html", {'form': form,})
    else:
        form = changeUser(instance = request.user)
        return render(request, "Users/editarUsuario.html", {'form': form,})
        
@login_required(login_url='/users/login')
def changePass(request):
    form = PasswordChangeForm(user=request.user, data=request.POST)
    if request.method == 'POST':        
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, request.user)
            context = {'form': form}
            return redirect(reverse_lazy('users:editarPerfil'))
        else:
            return render(request, "Users/changePassword.html", {'form': form,})
    else:
    	form = PasswordChangeForm(user=request.user)
    return render(request, "Users/changePassword.html", {'form': form,})
        
@user_passes_test(lambda u: u.is_superuser)
@login_required(login_url='/users/login')
def editUser(request, id_usuario):
    usuario = User.objects.get(id=id_usuario)
    if request.method == 'POST':        
	form = editUserA(request.POST, instance=usuario)
	
        if form.is_valid():
            form.save()
            context = {'form': form}
            return render(request, "Users/edit_form.html", {'form': form,})
        else:
            return render(request, "Users/edit_form.html", {'form': form,})
    else:
        form = editUserA(instance=usuario)
        return render(request, "Users/edit_form.html", {'form': form,})


@login_required(login_url='/users/login')
@user_passes_test(lambda u: u.is_superuser)
def editarUsuarios(request):
    usuarios = User.objects.all()

    paginator = Paginator(usuarios, 10)

    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1

    try:
        posts = paginator.page(page)
    except(EmptyPage, InvalidPage):
        posts = paginator.page(paginator.num_pages)

    context = RequestContext(request, {'usuarios': posts})
    return render_to_response('Users/editarUsuarios.html', {'usuarios': posts},
                              context_instance=RequestContext(request))


@login_required(login_url='/users/login')
@user_passes_test(lambda u: u.is_superuser)
def borrarUsuario(request, id_u):
    usuario = User.objects.get(id=id_u)
    usuario.delete()
    return redirect(reverse_lazy('users:editarUsuarios'))

ProyectoJR/Users/templates/Users/changePassword.html
{% extends "base.html" %}

{% block login %}
	<div style="margin: 0 auto; display:table;">
	<style type="text/css">
	      
	      .form-signin {
		max-width: 300px;
		padding: 19px 29px 29px;
		margin: 0 auto 20px;
		background-color: #fff;
		border: 1px solid #e5e5e5;
		-webkit-border-radius: 5px;
		   -moz-border-radius: 5px;
		        border-radius: 5px;
		-webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
		   -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
		        box-shadow: 0 1px 2px rgba(0,0,0,.05);
	      }
	      .form-signin .form-signin-heading,
	      .form-signin .checkbox {
		margin-bottom: 10px;
	      }
	      .form-signin input[type="text"],
	      .form-signin input[type="password"] {
		font-size: 16px;
		height: auto;
		margin-bottom: 15px;
		padding: 7px 9px;
		background-color: #ffffff !important;
		border: 1px solid #cccccc;
	      }
    </style>
				
		<form class="form-signin" action='' method="POST">
			{% csrf_token %}	
			<h2 class="form-signin-heading">Cambiar pass</h2>
			<input name="old_password" type="password" class="input-block-level" placeholder="Contraseña antigua">
			<input name="new_password1" type="password" class="input-block-level" placeholder="Nueva contraseña">
			<input name="new_password2" type="password" class="input-block-level" placeholder="Repita contraseña">			
			{% if form.errors %}
			    {% for field in form %}
				{% for error in field.errors %}
				    <div class="alert alert-danger">
					{{ error|escape }}
				    </div>
				{% endfor %}
			    {% endfor %}
			    {% for error in form.non_field_errors %}
				<div class="alert alert-danger">
				    {{ error|escape }}
				</div>
			    {% endfor %}
			{% endif %}				
			<button class="btn btn-large btn-primary" type="submit" style="width:100%">Cambiar</button>
			
		</form>
      
	</div>
{% endblock %}

ProyectoJR/Users/templates/Users/edit_form.html
{% extends 'base.html' %}
	
{% block formInsertar %}
	<div style="margin: 0 auto; display:table;">
	<style type="text/css">
	      
	      .form-signin {
		max-width: 300px;
		padding: 19px 29px 29px;
		margin: 0 auto 20px;
		background-color: #fff;
		border: 1px solid #e5e5e5;
		-webkit-border-radius: 5px;
		   -moz-border-radius: 5px;
		        border-radius: 5px;
		-webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
		   -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
		        box-shadow: 0 1px 2px rgba(0,0,0,.05);
	      }
	      .form-signin .form-signin-heading,
	      .form-signin .checkbox {
		margin-bottom: 10px;
	      }
	      .form-signin input[type="text"],
	      .form-signin input[type="password"],
      	      .form-signin input[type="email"] {
		font-size: 16px;
		height: auto;
		margin-bottom: 15px;
		padding: 7px 9px;
		background-color: #ffffff !important;
		border: 1px solid #cccccc;
	      }
    </style>
    <h2>Editar Usuario</h2>
	<form class="form-signin" action='' method="POST">
		{% csrf_token %}
		{{form.as_p}}
		<button class="btn btn-large btn-primary" type="submit">Editar</button>
	</form>
	</div>
	<div class="clear"></div>
{% endblock %}

ProyectoJR/Users/templates/Users/editarUsuario.html
{% extends 'base.html' %}
	
{% block formInsertar %}
	<div style="margin: 0 auto; display:table;">
	<style type="text/css">
	      
	      .form-signin {
		max-width: 300px;
		padding: 19px 29px 29px;
		margin: 0 auto 20px;
		background-color: #fff;
		border: 1px solid #e5e5e5;
		-webkit-border-radius: 5px;
		   -moz-border-radius: 5px;
		        border-radius: 5px;
		-webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
		   -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
		        box-shadow: 0 1px 2px rgba(0,0,0,.05);
	      }
	      .form-signin .form-signin-heading,
	      .form-signin .checkbox {
		margin-bottom: 10px;
	      }
	      .form-signin input[type="text"],
	      .form-signin input[type="password"],
      	      .form-signin input[type="email"] {
		font-size: 16px;
		height: auto;
		margin-bottom: 15px;
		padding: 7px 9px;
		background-color: #ffffff !important;
		border: 1px solid #cccccc;
	      }
    </style>
    <h2>Editar Usuario</h2>
	<form class="form-signin" action='' method="POST">
		{% csrf_token %}
		{{form.as_p}}
		<button class="btn btn-large btn-primary" type="submit">Editar</button>
	</form>
	</div>
	<div class="clear"></div>
{% endblock %}

ProyectoJR/Users/templates/Users/editarUsuarios.html
	{% extends 'base.html' %}
	
		{% block content %}
			
			{% if user.is_superuser %}
			<div class="row" style="margin-left:5px;margin-right:5px;">
			<div class='col-xs-24 col-sm-12 col-md-12 col-lg-12'>			
				<h2>Usuarios</h2>				
								
			
			{% if usuarios %}
			
				<div class='main section' id='main' style="margin-top:10px;">
					<div class='widget Blog' id='Blog1'>
						<div id='list-main'>
						
							<table class="table table-bordered table-striped">
							<tr>
							<th style="text-align:center;">Id</th>
							<th>Username</th>
							<th>Tipo</th>								
							<th style="text-align:center;">Borrar</th>	
							</tr>
							{% for c in usuarios %}
								<tr>
								<td style="text-align:center;">{{ c.id }}</td>
								<td><a href="{% url 'users:editarUsuario' c.id %}">{{ c.username }}</a></td>
								<td>	{% if c.is_superuser %}
									Administrador									
									{% elif c.is_staff %}
									Autor									
									{% else %}
									Invitado									
									{% endif %}
								</td>
								<td style="text-align:center;"><a onclick="return confirm('¿ Deseas borrar este usuario ?')" href="{% url 'users:borrarUsuario' c.id %}"><span style="color:#f44336;" class="glyphicon glyphicon-trash" aria-hidden="true"></span></a></td>
								</tr>
							{% endfor %}
							</table>
						
						</div>
						
					</div>
				
		      <ul class="pagination" style="margin-top:0px;margin-bottom:10px;">
			  {% if usuarios.has_previous %}
			      <li><a href="?page={{ usuarios.previous_page_number }}">Anterior</a></li>
			  {% endif %}
			  {% for pg in usuarios.paginator.page_range %}
			      {% if usuarios.number == pg %}
				  <li class="active"><a href="?page={{ pg }}">{{ pg }}</a></li>
			      {% else %}
				  <li><a href="?page={{ pg }}">{{ pg }}</a></li>
			      {% endif %}
			  {% endfor %}
			  {% if usuarios.has_next %}
			      <li><a href="?page={{ usuarios.next_page_number }}">Siguiente</a></li>
			  {% endif %}
		      </ul>
		      
		      </div>
				<!-- END Loop -->
		      </div>	
			{% endif %}
			</div> 
			{% endif %} 
		 {% endblock content %}	

ProyectoJR/Users/templates/Users/login_form.html
{% extends "base.html" %}

{% block login %}
	<div style="margin: 0 auto; display:table;">
	<style type="text/css">
	      
	      .form-signin {
		max-width: 300px;
		padding: 19px 29px 29px;
		margin: 0 auto 20px;
		background-color: #fff;
		border: 1px solid #e5e5e5;
		-webkit-border-radius: 5px;
		   -moz-border-radius: 5px;
		        border-radius: 5px;
		-webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
		   -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
		        box-shadow: 0 1px 2px rgba(0,0,0,.05);
	      }
	      .form-signin .form-signin-heading,
	      .form-signin .checkbox {
		margin-bottom: 10px;
	      }
	      .form-signin input[type="text"],
	      .form-signin input[type="password"] {
		font-size: 16px;
		height: auto;
		margin-bottom: 15px;
		padding: 7px 9px;
		background-color: #ffffff !important;
		border: 1px solid #cccccc;
	      }
    </style>
				
		<form class="form-signin" action='' method="POST">
			{% csrf_token %}	
			<h2 class="form-signin-heading">Login</h2>
			<input name="username" type="text" class="input-block-level" placeholder="Nombre de Usuario">
			<input name="password" type="password" class="input-block-level" placeholder="Password">
			<label class="checkbox" style="margin-left:20px;font-weight:100">
				<input type="checkbox" value="remember-me"> Recuerdame
			</label>
			{% if form.errors %}
			    {% for field in form %}
				{% for error in field.errors %}
				    <div class="alert alert-danger">
					{{ error|escape }}
				    </div>
				{% endfor %}
			    {% endfor %}
			    {% for error in form.non_field_errors %}
				<div class="alert alert-danger">
				    {{ error|escape }}
				</div>
			    {% endfor %}
			{% endif %}				
			<button class="btn btn-large btn-primary" type="submit" style="width:100%">Entrar</button>
			<label style="margin-top: 10px;font-weight:100;">
				<a href="{% url 'users:registro' %}">Registrate</a>
				<a href="" style="margin-left: 25px;">¿Olvido de contraseña?</a>				
			</label>
		</form>
      
	</div>
{% endblock %}

ProyectoJR/Users/templates/Users/registro_form.html
{% extends "base.html" %}

{% block login %}
	<div style="margin: 0 auto; display:table;">
	<style type="text/css">
	      
	      .form-signin {
		max-width: 300px;
		padding: 19px 29px 29px;
		margin: 0 auto 20px;
		background-color: #fff;
		border: 1px solid #e5e5e5;
		-webkit-border-radius: 5px;
		   -moz-border-radius: 5px;
		        border-radius: 5px;
		-webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
		   -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
		        box-shadow: 0 1px 2px rgba(0,0,0,.05);
	      }
	      .form-signin .form-signin-heading,
	      .form-signin .checkbox {
		margin-bottom: 10px;
	      }
	      .form-signin input[type="text"],
	      .form-signin input[type="password"] {
		font-size: 16px;
		height: auto;
		margin-bottom: 15px;
		padding: 7px 9px;
		background-color: #ffffff !important;
		border: 1px solid #cccccc;
	      }
    </style>
				
		<form class="form-signin" action='' method="POST">
			{% csrf_token %}
			<h2 class="form-signin-heading">Registro</h2>
			<input name="email" type="text" class="input-block-level" placeholder="Email">
			<input name="username" type="text" class="input-block-level" placeholder="Nombre de Usuario">
			<input name="password1" type="password" class="input-block-level" placeholder="Password">
			<input name="password2" type="password" class="input-block-level" placeholder="Repite password">
			<input name="first_name" type="text" class="input-block-level" placeholder="Nombre">
			<input name="last_name" type="text" class="input-block-level" placeholder="Apellidos">						
			{% if form.errors %}
			    {% for field in form %}
				{% for error in field.errors %}
				    <div class="alert alert-danger">
					{{ error|escape }}
				    </div>
				{% endfor %}
			    {% endfor %}
			    {% for error in form.non_field_errors %}
				<div class="alert alert-danger">
				    {{ error|escape }}
				</div>
			    {% endfor %}
			{% endif %}			
			<button class="btn btn-large btn-primary" type="submit" style="width:100%">Registrate</button>
		</form>
      
	</div>
{% endblock %}