ProyectoJR/Blog/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from Blog.views import editarNoticiasClass
from Blog import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^new',views.insertar_noticia, name = 'InsertarNoticia'),
    url(r'^(?P<noticia_id>\d+)$', views.mostrar_noticia, name ='MostrarNoticia'),
    url(r'^edit/(?P<id_noticia>\d+)$',views.editarNoticia, name = 'EditarNoticia'),
    url(r'^borrar/(?P<noticia>\d+)$',views.borrarNoticia, name = 'BorrarNoticia'),
    #url(r'^',views.editarNoticias, name = 'EditarNoticias'),
    url(r'^$', login_required(editarNoticiasClass.as_view()), name = 'EditarNoticias'),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

ProyectoJR/ProyectoJR/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from Blog import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^noticias/',include('Blog.urls', namespace="urlNoticias")),
    url(r'^categoria/(?P<nombreCat>\w{0,50})$',views.categoria, name="filtro_categoria"),
    url(r'^categoria/borrar/(?P<Cat>\w{0,50})$',views.borrarCategoria, name="borrarCategoria"),
    url(r'^categoria/edit/(?P<id_categ>\w{0,50})$',views.editarCategoria, name="editarCategoria"),
    url(r'^categoria/new/', views.insertar_categoria, name="nuevaCategoria"),
    url(r'^categorias/', login_required(views.editarCategoriasClass.as_view()), name="Ccategoria"),
    url(r'^comentario/borrar/(?P<coment>\w{0,50})$',views.borrarComentario, name="borraComentario"),
    url(r'^comentarios/', login_required(views.editarComentariosClas.as_view()), name="comentario"),
    url(r'^autor/(?P<nombreAut>\w{0,50})/$',views.autor, name="autor"),
    url(r'^search/',views.search),
    url(r'^users/',include('Users.urls', namespace = "users")),
    url(r'^$',views.index, name = "index"),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

ProyectoJR/Blog/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Categoria(models.Model):
  Nombre = models.CharField(max_length = 100)
  def __unicode__(self):
    return self.Nombre

class Noticia(models.Model):
  Estados = (
        ('0', 'Desactivado'),
        ('1', 'Activado'),
  )
  Titulo = models.CharField(max_length = 200)
  SubTitulo = models.CharField(max_length = 500, null=True, blank=True)
  Contenido = models.TextField()
  Etiquetas = models.CharField(max_length = 100, null=True, blank=True)
  Imagen = models.ImageField(upload_to='img', null=True, blank=True)
  Fecha = models.DateTimeField(auto_now_add=True)
  Estado = models.CharField(max_length=1,choices=Estados)
  Categoria = models.ManyToManyField(Categoria, blank=True)
  Autor = models.ForeignKey(User)
  def __unicode__(self):
    return self.Titulo

class Comentario(models.Model):
  Estados = (
        ('0', 'Desactivado'),
        ('1', 'Activado'),
  )
  Texto = models.TextField()
  Nombre = models.CharField(max_length = 50)
  Apellidos = models.CharField(max_length = 100, null=True, blank=True)
  Email = models.EmailField()
  Estado = models.CharField(max_length=1,choices=Estados)
  Noticia = models.ForeignKey(Noticia)
  Fecha = models.DateTimeField(auto_now_add=True)
  class Meta:
        unique_together = (("Email", "Fecha"),)
  def __unicode__(self):
    return self.Texto

  
  

ProyectoJR/Blog/forms.py
#encoding: utf-8
from django.forms import ModelForm
from django import forms
from Blog.models import Noticia, Comentario, Categoria

class noticiaForm(forms.ModelForm):
  class Meta:
	model = Noticia    
	fields = ['Titulo','SubTitulo','Contenido','Etiquetas','Imagen','Categoria','Estado']
	
  def __init__(self, *args, **kwargs):
    super(noticiaForm, self).__init__(*args,**kwargs)
    self.fields['Titulo'].widget.attrs['class'] = 'form-control'
    self.fields['SubTitulo'].widget.attrs['class'] = 'form-control'
    self.fields['Contenido'].widget.attrs['class'] = 'form-control'
    self.fields['Etiquetas'].widget.attrs['class'] = 'form-control'
    self.fields['Imagen'].widget.attrs['class'] = 'form-control'
    self.fields['Categoria'].widget.attrs['class'] = 'form-control'
    self.fields['Estado'].widget.attrs['class'] = 'form-control'
    
class searchForm(ModelForm):
	class Meta:
		fields = ['q']
		
class comentarioForm(forms.ModelForm):
	class Meta:
		model = Comentario
		fields = ['Nombre','Apellidos','Email','Texto']
		
class categoriaForm(forms.ModelForm):
	class Meta:
		model = Categoria
		fields = ['Nombre']
	def __init__(self, *args, **kwargs):
   		super(categoriaForm, self).__init__(*args,**kwargs)
		self.fields['Nombre'].widget.attrs['class'] = 'form-control'

ProyectoJR/Blog/views.py
from itertools import chain

from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.core.urlresolvers import reverse_lazy
from django.db.models import Q
from django.http import Http404
from django.shortcuts import redirect, render_to_response, get_object_or_404
from django.shortcuts import render
from django.template import RequestContext
from django.views.generic import ListView

from Blog.forms import noticiaForm, comentarioForm, categoriaForm
from Blog.models import Noticia, Categoria, Comentario


# Create your views here.
@login_required(login_url='/users/login')
def insertar_noticia(request):
    if request.user.is_staff:
        if request.method == 'POST':
            form = noticiaForm(request.POST, request.FILES)
            if form.is_valid():
                formulario = form.save(commit=False)
                formulario.Autor_id = request.user.id
                formulario.save()
                for item in request.POST.getlist('Categoria'):
                    formulario.Categoria.add(item)
                return redirect(reverse_lazy('urlNoticias:EditarNoticias'))
        else:
            form = noticiaForm()
        context = {'form': form}
        return render(request, 'Blog/insertarNoticia.html', context)
    else:
        return redirect(reverse_lazy('index'))


@login_required(login_url='/users/login')
def insertar_categoria(request):
    if request.user.is_staff:
        if request.method == 'POST':
            form = categoriaForm(request.POST, request.FILES)
            if form.is_valid():
                form.save()
                return redirect(reverse_lazy('Ccategoria'))
        else:
            form = categoriaForm()
        context = {'form': form}
        return render(request, 'Blog/insertarCategoria.html', context)
    else:
        return redirect(reverse_lazy('index'))


def mostrar_noticia(request, noticia_id):
    noticia_list = get_object_or_404(Noticia, id=noticia_id)
    try:
        comentarios = Comentario.objects.filter(Noticia=noticia_id).order_by('Fecha').reverse()
    except Comentario.DoesNotExist:
        comentarios = None
    sidebar = Categoria.objects.all()[:5]
    autores = User.objects.filter(is_staff=True)

    if request.method == 'POST':
        form = comentarioForm(request.POST)

        if request.user.is_authenticated():
            usuario = User.objects.get(id=request.user.id)

            if not usuario.first_name:
                usuario.first_name = "John"

            if not usuario.first_name:
                usuario.last_name = "Doe"

            if not usuario.email:
                usuario.email = "johndoel@mail.com"

            data = {'Texto': request.POST['Texto'],
                    'Nombre': usuario.first_name,
                    'Apellidos': usuario.last_name,
                    'Email': usuario.email}

            form = comentarioForm(data)

            if form.is_valid():
                form = form.save(commit=False)
                form.Noticia = noticia_list
                form.save()

        else:
            if form.is_valid():
                formulario = form.save(commit=False)
                formulario.Estado = 'Activado'
                formulario.Noticia = noticia_list
                formulario.save()
                context = {'form': form, 'noticia': noticia_list, 'categorias': sidebar,
                           'autores': autores, 'comentarios': comentarios}
                return render(request, "Blog/mostrarNoticia.html", context)
    else:

        form = comentarioForm()

    paginator = Paginator(comentarios, 5)

    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1

    try:
        posts = paginator.page(page)
    except(EmptyPage, InvalidPage):
        posts = paginator.page(paginator.num_pages)

    context = {'form': form, 'noticia': noticia_list, 'categorias': sidebar, 'autores': autores, 'comentarios': posts}
    return render(request, "Blog/mostrarNoticia.html", context)


def index(request):
    noticias = Noticia.objects.order_by('Fecha').reverse().filter(Estado=1)
    sidebar = Categoria.objects.all()[:5]
    autores = User.objects.filter(is_staff=True)[:5]

    paginator = Paginator(noticias, 4)

    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1

    try:
        posts = paginator.page(page)
    except(EmptyPage, InvalidPage):
        posts = paginator.page(paginator.num_pages)

    context = {'noticias': posts, 'categorias': sidebar, 'autores': autores}
    return render_to_response('Blog/content.html', context, context_instance=RequestContext(request))


def categoria(request, nombreCat):
    noticias = Noticia.objects.order_by('Fecha').reverse().filter(Categoria__id=nombreCat)
    sidebar = Categoria.objects.all()[:5]
    autores = User.objects.filter(is_staff=True)[:5]

    paginator = Paginator(noticias, 4)

    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1

    try:
        posts = paginator.page(page)
    except(EmptyPage, InvalidPage):
        posts = paginator.page(paginator.num_pages)

    context = {'noticias': posts, 'categorias': sidebar, 'autores': autores}
    return render(request, "Blog/content.html", context)


def autor(request, nombreAut):
    noticias = Noticia.objects.order_by('Fecha').reverse().filter(Autor__id=nombreAut)
    sidebar = Categoria.objects.all()[:5]
    autores = User.objects.filter(is_staff=True)[:5]

    paginator = Paginator(noticias, 4)

    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1

    try:
        posts = paginator.page(page)
    except(EmptyPage, InvalidPage):
        posts = paginator.page(paginator.num_pages)

    context = {'noticias': posts, 'categorias': sidebar, 'autores': autores}
    return render(request, "Blog/content.html", context)

def search(request):
    sidebar = Categoria.objects.all()[:5]
    autores = User.objects.filter(is_staff=True)[:5]
    if 'q' in request.GET:
        noticias = Noticia.objects.order_by('Fecha').reverse().filter(
                Q(Titulo__contains=request.GET['q']) | Q(Contenido__contains=request.GET['q']))
        paginator = Paginator(noticias, 4)

        try:
            page = int(request.GET.get('page', '1'))
        except:
            page = 1

        try:
            posts = paginator.page(page)
        except(EmptyPage, InvalidPage):
            posts = paginator.page(paginator.num_pages)

        queries_without_page = request.GET.copy()
        if queries_without_page.has_key('page'):
            del queries_without_page['page']

        context = {'query': queries_without_page, 'noticias': posts, 'categorias': sidebar, 'autores': autores}
        return render(request, "Blog/content.html", context)
    else:
        context = {'categorias': sidebar, 'autores': autores}
        return render(request, "Blog/content.html", context)


class editarNoticiasClass(ListView):
    template_name = 'Blog/editarNoticias.html'
    context_object_name = 'noticias'
    paginate_by = 5

    def get_queryset(self):
        if self.request.user.is_superuser:
            return Noticia.objects.order_by('Fecha').reverse()
        else:
            if self.request.user.is_staff:
                return Noticia.objects.filter(Autor__id = self.request.user.id).order_by('Fecha').reverse()
            else:
                raise Http404

class editarCategoriasClass(ListView):
    template_name = 'Blog/editarCategorias.html'
    context_object_name = 'categorias'
    paginate_by = 5

    def get_queryset(self):
        if self.request.user.is_superuser or self.request.user.is_staff:
            return Categoria.objects.all()
        else:
            raise Http404

class editarComentariosClas(ListView):
    template_name = 'Blog/editarComentarios.html'
    context_object_name = 'comentarios'
    paginate_by = 5

    def get_queryset(self):
        if self.request.user.is_superuser:
            return Comentario.objects.all().order_by('Fecha').reverse()
        else:
            raise Http404

@login_required(login_url='/users/login')
def editarNoticia(request, id_noticia):
    if request.user.is_staff:
        noticias = get_object_or_404(Noticia, id=id_noticia)
        if request.method == 'POST':
            form = noticiaForm(request.POST, request.FILES, instance=noticias)
            if form.is_valid():
                formulario = form.save(commit=False)
                formulario.Categoria = request.POST.getlist('Categoria')
                formulario.Autor_id = request.user.id
                formulario.save()

                return render(request, 'Blog/editarNoticia.html', {'form': form})
        else:
            form = noticiaForm(instance=noticias)
        context = {'form': form}
        return render(request, 'Blog/editarNoticia.html', context)
    else:
        return redirect(reverse_lazy('index'))


@login_required(login_url='/users/login')
def editarCategoria(request, id_categ):
    if request.user.is_staff:
        categoria = Categoria.objects.get(id=id_categ)
        if request.method == 'POST':
            form = categoriaForm(request.POST, instance=categoria)
            if form.is_valid():
                formulario = form.save()
                return redirect(reverse_lazy('Ccategoria'))
        else:
            form = categoriaForm(instance=categoria)
        context = {'form': form}
        return render(request, 'Blog/editarCategoria.html', context)
    else:
        return redirect(reverse_lazy('index'))


@login_required(login_url='/users/login')
def borrarNoticia(request, noticia):
    if request.user.is_staff or request.user.is_superuser:
        noticias = get_object_or_404(Noticia, id=noticia)
        if noticias.Autor_id == request.user.id or request.user.is_superuser:

ProyectoJR/Blog/templates/Blog/content.html
{% extends 'base.html' %}

{% block content %}


    <div class='col-xs-12 col-sm-8 col-md-8 col-lg-8'>
        <div class='main section' id='main'>
            <div class='widget Blog' id='Blog1'>
                <div id='list-main'>
                    {% if noticias %}
                        {% for noticia in noticias %}
                            <div class='post-div'>
                                <h2 class='jqmaintitle'>
                                    <a href='{% url 'urlNoticias:MostrarNoticia' noticia.id %}'>
                                        {{ noticia.Titulo }}
                                    </a>                                
                                {% if noticia.SubTitulo %}
                                <p style="padding-bottom: 0px;font-size: 15px;margin-bottom: -10px;"><i>"{{ noticia.SubTitulo }}"</i></p>
                                {% endif %}
                                </h2>
                                <div class='post-header-home'>
									<span class='post-author vcard'>
									<span style="color:#666;" class="glyphicon glyphicon-user"
                                          aria-hidden="true"></span>
									Creado por 
									<a href='{% url 'autor' noticia.Autor.id %}' style="color:#666">
                                        {{ noticia.Autor }}
                                    </a>
                                        {% if noticia.Categoria.all %}
                                            en
                                            {% for cate in noticia.Categoria.all %}
                                                <a href='{% url 'filtro_categoria' cate.id %}' style="color:#666">
                                                    {{ cate.Nombre }}. 
                                                </a>
                                            {% endfor %}
                                        {% endif %}
									</span>
                                </div>
                                <div class='homapge-thumb'>
                                    <div class='post hentry' itemprop='blogPost' itemscope='itemscope'
                                         itemtype='http://schema.org/BlogPosting'>

                                        <div id='summary301858911604517742'>
                                            <div dir="ltr" style="text-align: left;" trbidi="on">
                                                {% if noticia.Imagen %}
                                                    <a href="{{ noticia.Imagen.url }}" imageanchor="1"
                                                       style="float:left;margin-right: 1em;"><img
                                                            src="{{ noticia.Imagen.url }}" class="img-responsive"
                                                            style="width:300px;"/></a>
                                                {% endif %}
                                                <p style="text-align:justify;">{{ noticia.Contenido|safe|truncatewords_html:"100" }}</p>
                                            </div>
                                        </div>

                                        <div class='s-clear'></div>
                                        <div class='rmlink'>
                                            <a href='{% url 'urlNoticias:MostrarNoticia' noticia.id %}'>
                                                Leer más
                                            </a>
                                        </div>
                                        <div class='s-clear'></div>
                                    </div>
                                </div>
                                <div class='post-header-label'>
									<span class='post-timestamp'>
									<span style="color:#666;" class="glyphicon glyphicon-time"
                                          aria-hidden="true"></span>
									{{ noticia.Fecha }}
									</span>
                                    {% if noticia.Etiquetas %}
                                        <span class='post-labels'>
									<span class="glyphicon glyphicon-tags" aria-hidden="true"
                                          style="margin-left:10px;margin-right:5px;"></span>
										{{ noticia.Etiquetas }}
									</span>
                                    {% endif %}
                                </div>
                            </div>
                        {% endfor %}
                        <ul class="pagination" style="margin-top:0px;margin-bottom:10px;">
                            {% if noticias.has_previous %}
                                <li><a href="?{{query.urlencode}}&amp;page={{ noticias.previous_page_number }}">Anterior</a></li>
                            {% endif %}
                            {% for pg in noticias.paginator.page_range %}
                                {% if noticias.number == pg %}
                                    <li class="active"><a href="?{{query.urlencode}}&amp;page={{ pg }}">{{ pg }}</a></li>
                                {% else %}
                                    <li><a href="?{{query.urlencode}}&amp;page={{ pg }}">{{ pg }}</a></li>
                                {% endif %}
                            {% endfor %}
                            {% if noticias.has_next %}
                                <li><a href="?{{query.urlencode}}&amp;page={{ noticias.next_page_number }}">Siguiente</a></li>
                            {% endif %}
                        </ul>
                    {% else %}

                        <h1 style="text-align:center;font-size:30px;">¡No hay entradas!</h1>

                    {% endif %}
                </div>

            </div>
        </div>
        <!-- END Loop -->
    </div>

    <div class='col-xs-12 col-sm-4 col-md-4 col-lg-4 hide-home-sidebar'>
        <div class='sidebox'>
            <div class='sidebar section' id='sidebar'>
                <div class='widget Label' id='Label2'>
                    <h2 class='title'>
                        Busqueda
                    </h2>
                    <div class='widget-content list-label-widget-content'>

                        <form action='/search/' class='navbar-form' method='GET' role='search'>
                            {% csrf_token %}
                            <input class='form-control form-main-search' name='q' placeholder='Buscar ...' type='text'
                                   style="width:98%"/>
                            <button class='btn btn-def' type='submit'></button>
                        </form>

                    </div>
                </div>
                {% if autores %}
                    <div class='widget Label' id='Label2'>
                        <h2 class='title'>
                            Autores
                        </h2>
                        <div class='widget-content list-label-widget-content'>
                            <ul>
                                {% for au in autores %}
                                    <li>
                                        <a href="{% url 'autor' au.id %}">
                                            {{ au.username }}
                                        </a>
                                    </li>
                                {% endfor %}

                            </ul>
                        </div>
                    </div>
                {% endif %}
                {% if categorias %}
                    <div class='widget Label' id='Label1'>
                        <h2>
                            Categorias
                        </h2>
                        <div class='widget-content list-label-widget-content'>
                            <ul>
                                {% for cat in categorias %}
                                    <li>
                                        <a href="{% url 'filtro_categoria' cat.id %}">
                                            {{ cat.Nombre }}
                                        </a>
                                    </li>
                                {% endfor %}

                            </ul>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock content %}

ProyectoJR/Blog/templates/Blog/editarCategoria.html
{% extends 'base.html' %}
	
{% block formInsertar %}
	<h2>Editar Categoria</h2>
	<form id="form" method="POST" enctype="multipart/form-data" action="" style="background-color:white;padding:20px;border-radius:5px;margin-bottom:20px;">
		{% csrf_token %}
		{{form}}
		<button class="btn btn-large btn-primary" type="submit" style="margin-top: 10px;">Editar</button>
	</form>
{% endblock %}

ProyectoJR/Blog/templates/Blog/editarComentarios.html
	{% extends 'base.html' %}
	
		{% block content %}
			
			{% if user.is_superuser %}
			<div class="row" style="margin-left:5px;margin-right:5px;">
			<div class='col-xs-24 col-sm-12 col-md-12 col-lg-12'>			
				<h2>Comentarios</h2>				
								
			
			{% if comentarios %}
			
				<div class='main section' id='main' style="margin-top:10px;">
					<div class='widget Blog' id='Blog1'>
						<div id='list-main'>
						
							<table class="table table-bordered table-striped">
							<tr>
							<th style="text-align:center;">Id</th>
							<th>Comentario</th>
							<th>Noticia</th>
							<th>Fecha</th>								
							<th style="text-align:center;">Borrar</th>	
							</tr>
							{% for c in comentarios %}
								<tr>
								<td style="text-align:center;">{{ c.id }}</td>
								<td>{{ c.Texto }}</td>
								<td><a href="{% url 'urlNoticias:MostrarNoticia' c.Noticia.id %}">{{ c.Noticia }}</a></td>
								<td>{{ c.Fecha }}</td>
								<td style="text-align:center;"><a href="{% url 'borraComentario' c.id %}" onclick="return confirm('¿ Deseas borrar este comentario ?')"><span style="color:#f44336;" class="glyphicon glyphicon-trash" aria-hidden="true"></span></a></td>
								</tr>
							{% endfor %}
							</table>
						
						</div>
						
					</div>
				
		      {% if is_paginated %}
		      <ul class="pagination" style="margin-top:0px;margin-bottom:10px;">
			  {% if page_obj.has_previous %}
			      <li><a href="?page={{ page_obj.previous_page_number }}">Anterior</a></li>
			  {% endif %}
			  {% for pg in page_obj.paginator.page_range %}
			      {% if page_obj.number == pg %}
				  <li class="active"><a href="?page={{ pg }}">{{ pg }}</a></li>
			      {% else %}
				  <li><a href="?page={{ pg }}">{{ pg }}</a></li>
			      {% endif %}
			  {% endfor %}
			  {% if page_obj.has_next %}
			      <li><a href="?page={{ page_obj.next_page_number }}">Siguiente</a></li>
			  {% endif %}
		      </ul>
		      {% endif %}
		      
		      </div>
				<!-- END Loop -->
		      </div>	
			{% endif %}
			</div> 
			{% endif %} 
		 {% endblock content %}	

ProyectoJR/Blog/templates/Blog/editarNoticia.html
{% extends 'base.html' %}
	
{% block formInsertar %}
	<h2>Editar Noticia</h2>
	<form id="form" method="POST" enctype="multipart/form-data" action="" style="background-color:white;padding:20px;border-radius:5px;margin-bottom:20px;">
		{% csrf_token %}
		{{ foobar|safe }}
		{{form}}
		<button class="btn btn-large btn-primary" type="submit" style="margin-top: 20px;">Editar</button>
	</form>
{% endblock %}

ProyectoJR/Blog/templates/Blog/editarNoticias.html
	{% extends 'base.html' %}
	
		{% block content %}
			<div class="row" style="margin-left:5px;margin-right:5px;">
			<div class='col-xs-24 col-sm-12 col-md-12 col-lg-12'>
				<h2>Noticias</h2>
				<a href="{% url 'urlNoticias:InsertarNoticia' %}" style="color:white;background:#4d8b97;padding: 7px;border-radius: 100px;text-decoration: none;"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Nueva noticia</a>

			{% if noticias %}
			
				<div class='main section' id='main' style="margin-top:10px;">
					<div class='widget Blog' id='Blog1'>
						<div id='list-main'>
						
							<table class="table table-bordered table-striped">
							<tr>
							<th style="text-align:center;">Id</th>
							<th>Titulo</th>	
							<th style="text-align:center;">Borrar</th>	
							</tr>
							{% for n in noticias %}
								<tr>
								<td style="text-align:center;">{{ n.id }}</td>
								<td><a href="{% url 'urlNoticias:EditarNoticia' n.id %} ">{{ n.Titulo }}</a></td>
								<td style="text-align:center;"><a href="{% url 'urlNoticias:BorrarNoticia' n.id %}" onclick="return confirm('¿ Deseas borrar esta entrada ?')"><span style="color:#f44336;" class="glyphicon glyphicon-trash" aria-hidden="true"></span></a></td>
								</tr>
							{% endfor %}
							</table>
						
						</div>
						
					</div>
				
					
		    {% if is_paginated %}
		      <ul class="pagination" style="margin-top:0px;margin-bottom:10px;">
			  {% if page_obj.has_previous %}
			      <li><a href="?page={{ page_obj.previous_page_number }}">Anterior</a></li>
			  {% endif %}
			  {% for pg in page_obj.paginator.page_range %}
			      {% if page_obj.number == pg %}
				  <li class="active"><a href="?page={{ pg }}">{{ pg }}</a></li>
			      {% else %}
				  <li><a href="?page={{ pg }}">{{ pg }}</a></li>
			      {% endif %}
			  {% endfor %}
			  {% if page_obj.has_next %}
			      <li><a href="?page={{ page_obj.next_page_number }}">Siguiente</a></li>
			  {% endif %}
		      </ul>
		      {% endif %}
		      </div>
				<!-- END Loop -->
		      </div>	
			{% endif %}
			</div>  
		 {% endblock content %}	

ProyectoJR/Blog/templates/Blog/insertarCategoria.html
{% extends 'base.html' %}
	
{% block formInsertar %}
	<h2>Insertar Categoria</h2>
	<form id="form" method="POST" enctype="multipart/form-data" action="" style="background-color:white;padding:20px;border-radius:5px;margin-bottom:20px;">
		{% csrf_token %}
		{{form.as_p}}
		<button class="btn btn-large btn-primary" type="submit">Insertar</button>
	</form>
	<div class="clear"></div>
{% endblock %}

ProyectoJR/Blog/templates/Blog/insertarNoticia.html
{% extends 'base.html' %}
	
{% block formInsertar %}
	<h2>Insertar Noticia</h2>
	<form id="form" method="POST" enctype="multipart/form-data" action="" style="background-color:white;padding:20px;border-radius:5px;margin-bottom:20px;">
		{% csrf_token %}
		{{ foobar|safe }}
		{{form.as_p}}
		<button class="btn btn-large btn-primary" type="submit">Publicar</button>
	</form>
	<div class="clear"></div>
{% endblock %}